---
source:
  server: tcp://pubsub.besteffort.ndovloket.nl:7664
  envelopes:
    arrivals: "/RIG/InfoPlusDASInterface4"
    departures: "/RIG/InfoPlusDVSInterface4"
    services: "/RIG/InfoPlusRITInterface2"
api:
  address: ":8080"
stores:
  location: /tmp/gotrain/
archive:
  endpoint: http://localhost:1000
prometheus:
  enabled: true
  address: :2121
#sentry:
#  dsn: https://example@sentry.io/123456
#  warnings: true
#  environment: production
